### ISSUE TITLE
Add API Requests to Repo

### ISSUE THREAD

**Issue by geoss** [beckymasond/suffolk_USGS#1]
Add the code with the census API requests to the repository, not just the data.  Presumably if the API code is in here the data itself need not be stored in the repository.

**Comment by beckymasond** [comment]
Yes, that's on my to do list. I haven't had time to get it fully commented
and easy to run for all the selected variables but wanted to make sure Joe
at least had the data to start. I'll have it up within the next few days.

On Monday, February 15, 2016, Seth Spielman notifications@github.com
wrote:

> Assigned #1 https://github.com/beckymasond/suffolk_USGS/issues/1 to
> @beckymasond https://github.com/beckymasond.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beckymasond/suffolk_USGS/issues/1#event-551052464.

## 

Rebecca Davies
Master's degree student
Dept. of Geography
CU Boulder

**Comment by beckymasond** [comment]
Also on my list is adding more descriptive info to the main page but I
haven't had time yet for this either -- I'll also try to have that done
within a few days along with more description for each individual file.

On Monday, February 15, 2016, Rebecca M Davies <
Rebecca.M.Davies@colorado.edu> wrote:

> Yes, that's on my to do list. I haven't had time to get it fully commented
> and easy to run for all the selected variables but wanted to make sure Joe
> at least had the data to start. I'll have it up within the next few days.
> 
> On Monday, February 15, 2016, Seth Spielman <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Assigned #1 https://github.com/beckymasond/suffolk_USGS/issues/1 to
> > @beckymasond https://github.com/beckymasond.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/beckymasond/suffolk_USGS/issues/1#event-551052464.
> 
> ## 
> 
> Rebecca Davies
> Master's degree student
> Dept. of Geography
> CU Boulder

## 

Rebecca Davies
Master's degree student
Dept. of Geography
CU Boulder

**Comment by geoss** [comment]
Yup.  Just added issue for tracking TODO items.

**Comment by beckymasond** [comment]
Ah, right, I have yet to take advantage of all the GitHub features! I'll
add my other to do items to that list so that they are fully visible.
Thanks.

On Mon, Feb 15, 2016 at 12:40 PM, Seth Spielman notifications@github.com
wrote:

> Yup. Just added issue for tracking TODO items.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beckymasond/suffolk_USGS/issues/1#issuecomment-184358445
> .

## 

Rebecca Davies
Master's degree student
Dept. of Geography
CU Boulder
