### ISSUE TITLE
Clarify the purpose and use of each script 

### ISSUE THREAD

**Issue by geoss** [beckymasond/suffolk_USGS#2]
It is not at all clear what the files in the repository do.  Please add a block at the top of each file clearly explaining its purpose, inputs, and outputs.  Something like: [https://www.cs.siue.edu/programming-style-guide](https://www.cs.siue.edu/programming-style-guide)

**Comment by jvtcl** [comment]
The link is dead...

**Comment by geoss** [comment]
Its up now.  It was just an example.  First thing that came up on google.

**Comment by jvtcl** [comment]
Descriptions are up. Let me know if anything needs more detail.
