### ISSUE TITLE
Update ReadMe and file metadata

### ISSUE THREAD

**Issue by beckymasond** [beckymasond/suffolk_USGS#3]

**Comment by beckymasond** [comment]
@jtuccill I started adding some basic content to the ReadMe file. Feel free to edit and add to it.

**Comment by beckymasond** [comment]
@jtuccill Where can I add metadata for the csv files such that it won't interfere with your data processing? Top or bottom of file? Or should I just include separate files in each folder?

**Comment by jvtcl** [comment]
Let's add the metadata as separate files. CSV files can only handle a limited amount of additional information (i.e. a brief header that gets ignored when the file is read into R).

**Comment by beckymasond** [comment]
Added metadata .txt files to every data folder containing the raw ACS data.
