### ISSUE TITLE
Replace 'master_vars.xlsx' with a CSV version

### ISSUE THREAD

**Issue by jvtcl** [beckymasond/suffolk_USGS#5]
Please replace 'master_vars.xlsx' with a CSV version. I'd like to use the file as a key for automating the data prep stage. I'm running into errors using the 'gdata' library to read the .xlsx file into R. Replacing this step with 'read.csv' would simplify things greatly. @beckymasond

**Comment by jvtcl** [comment]
I noticed that there are blank entries in 'master_vars.csv' where cells had been merged in the xlsx file. These entries need to be filled in so that grouped variables can be referenced properly for aggregation.

**Comment by beckymasond** [comment]
For all data that had been in merged rows in the Excel file, I copied them into each line in the csv.
