### ISSUE TITLE
Identify alternate variable for poverty ratio 

### ISSUE THREAD

**Issue by beckymasond** [beckymasond/suffolk_USGS#6]
The Poverty Ratio variable in Social Explorer data is not available at the block group level due to ACS data suppression (most likely for confidentiality reasons). We need to identify a different measure of poverty to use as a substitute variable.

**Comment by geoss** [comment]
Does poverty rate exist?  If that's suppressed how about the "not in poverty rate" (1-povertyrate)

**Comment by beckymasond** [comment]
There are values for the total population with income in the past 12 months below poverty level (subdivided by various attributes), but I also identified an ACS equivalent to the Social Explorer variable we were using. It is essentially the same measure but with different break points between categories. I have added this revised data to the "rawACSdata_poverty" folder and recently updated the master_vars csv and the acs_dataprep script to reflect this change, and next will update the data dictionary. I have also replaced the occupancy variable (B25026) with similar data that is available at the block group level (B25038).
