### ISSUE TITLE
Update data dictionary estimate names to match updated 'master_vars.csv'

### ISSUE THREAD

**Issue by jvtcl** [beckymasond/suffolk_USGS#7]
@beckymasond There is some mismatch between the estimate names for 'data/data_dict.csv' and 'master_vars.csv': 

![vars_mismatch](https://cloud.githubusercontent.com/assets/10080304/13304245/c2e16578-db10-11e5-863f-1c64f0697d29.PNG)

('group.key' is the data frame read in from 'master_vars.csv')

Also, I noticed that the income/poverty ratio vars are estimated for 2009. Just want to verify that these were pulled from the 2014 ACS estimates...

**Comment by beckymasond** [comment]
The way I originally set up the master_vars list I just left your
information from 2009 and added the modifications for the 2014 data in the
right-most column. So I think what's happening is that the 2009 variables
in master_vars are being compared to the 2014 variables in data_dict. I
think this was just a miscommunication -- I initially thought the data
dictionary would be your main variable reference and that the master_vars
sheet was just to compare 2009 and 2014 variables. I will remove the 2009
data entirely from the master_vars csv and that may resolve this issue.

However, I'm not sure if any of the phrases in the pasted code are from
data_dict. The data_dict and the 2014 column in the master_vars list
specify the terms exactly as they are in the ACS data. For example, the
data_dict specifies "Housing Stock built 1990-1999," so neither of the
phrases in line 1 match the data_dict. If that doesn't make sense let me
know. In either case, I will post a modified master_vars with only 2009
data and with the updated poverty ratio measures this afternoon.

On Wed, Feb 24, 2016 at 4:04 PM, jtuccill notifications@github.com wrote:

> @beckymasond https://github.com/beckymasond There is some mismatch
> between the estimate names for 'data/data_dict.csv' and 'master_vars.csv':
> 
> > group.key$Estimate[!group.key$Estimate %in% data.dict$Name]
> > [1] "Housing Stock built 1980-1990" "Housing Stock built 1990-2000"
> > [3] "Housing Stock built 2000-2004" "Single-Unit, detached"
> > [5] "Ratio Of Income in 2009 To Poverty Level: Under 0.5" "Ratio Of Income
> > in 2009 To Poverty Level: 0.5 - 0.74"
> > [7] "Ratio Of Income in 2009 To Poverty Level: 0.75 - 0.99" "Ratio Of
> > Income in 2009 To Poverty Level: 1 - 1.49"
> > [9] "Ratio Of Income in 2009 To Poverty Level: 0.75 - 0.99" "Ratio Of
> > Income in 2009 To Poverty Level: 1 - 1.49"
> > [11] "$10k-15k" "$15k-20k"
> > [13] "$20k-25k" "$25k-30k"
> > [15] "$30k-$35k" "$35k-40k"
> > [17] "$40k-50k" "$50k-60k"
> > [19] "$60k-70k" "$70k-80k"
> > [21] "$80k-90k" "$90k-100k"
> > [23] "$100k-125k" "$125k-150k"
> > [25] "$150k-175k" "$175k-200k"
> > [27] "$200k-250k" "$250k-300k"
> > [29] "$300k-400k" "$400k-500k"
> > [31] "$500k-750k" "$750k-1m"
> > [33] "$1m or more"
> 
> Also, I noticed that the income/poverty ratio vars are estimated for 2009.
> Just want to verify that these were pulled from the 2014 ACS estimates...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beckymasond/suffolk_USGS/issues/7.

## 

Rebecca Davies
Master's degree student
Dept. of Geography
CU Boulder

**Comment by beckymasond** [comment]
Oops I meant to say "In either case, I will post a modified master_vars
with only\* 2014 *data..."

On Wed, Feb 24, 2016 at 4:21 PM, Rebecca M Davies <
Rebecca.M.Davies@colorado.edu> wrote:

> The way I originally set up the master_vars list I just left your
> information from 2009 and added the modifications for the 2014 data in the
> right-most column. So I think what's happening is that the 2009 variables
> in master_vars are being compared to the 2014 variables in data_dict. I
> think this was just a miscommunication -- I initially thought the data
> dictionary would be your main variable reference and that the master_vars
> sheet was just to compare 2009 and 2014 variables. I will remove the 2009
> data entirely from the master_vars csv and that may resolve this issue.
> 
> However, I'm not sure if any of the phrases in the pasted code are from
> data_dict. The data_dict and the 2014 column in the master_vars list
> specify the terms exactly as they are in the ACS data. For example, the
> data_dict specifies "Housing Stock built 1990-1999," so neither of the
> phrases in line 1 match the data_dict. If that doesn't make sense let me
> know. In either case, I will post a modified master_vars with only 2009
> data and with the updated poverty ratio measures this afternoon.
> 
> On Wed, Feb 24, 2016 at 4:04 PM, jtuccill notifications@github.com
> wrote:
> 
> > @beckymasond https://github.com/beckymasond There is some mismatch
> > between the estimate names for 'data/data_dict.csv' and 'master_vars.csv':
> > 
> > > group.key$Estimate[!group.key$Estimate %in% data.dict$Name]
> > > [1] "Housing Stock built 1980-1990" "Housing Stock built 1990-2000"
> > > [3] "Housing Stock built 2000-2004" "Single-Unit, detached"
> > > [5] "Ratio Of Income in 2009 To Poverty Level: Under 0.5" "Ratio Of
> > > Income in 2009 To Poverty Level: 0.5 - 0.74"
> > > [7] "Ratio Of Income in 2009 To Poverty Level: 0.75 - 0.99" "Ratio Of
> > > Income in 2009 To Poverty Level: 1 - 1.49"
> > > [9] "Ratio Of Income in 2009 To Poverty Level: 0.75 - 0.99" "Ratio Of
> > > Income in 2009 To Poverty Level: 1 - 1.49"
> > > [11] "$10k-15k" "$15k-20k"
> > > [13] "$20k-25k" "$25k-30k"
> > > [15] "$30k-$35k" "$35k-40k"
> > > [17] "$40k-50k" "$50k-60k"
> > > [19] "$60k-70k" "$70k-80k"
> > > [21] "$80k-90k" "$90k-100k"
> > > [23] "$100k-125k" "$125k-150k"
> > > [25] "$150k-175k" "$175k-200k"
> > > [27] "$200k-250k" "$250k-300k"
> > > [29] "$300k-400k" "$400k-500k"
> > > [31] "$500k-750k" "$750k-1m"
> > > [33] "$1m or more"
> > 
> > Also, I noticed that the income/poverty ratio vars are estimated for
> > 2009. Just want to verify that these were pulled from the 2014 ACS
> > estimates...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/beckymasond/suffolk_USGS/issues/7.
> 
> ## 
> 
> Rebecca Davies
> Master's degree student
> Dept. of Geography
> CU Boulder

## 

Rebecca Davies
Master's degree student
Dept. of Geography
CU Boulder

**Comment by beckymasond** [comment]
I have modified the master_vars list and believe it is now ready, but I'll leave this issue open until you have a chance to verify everything matches up properly.
