### ISSUE TITLE
Fix ACS total codes in 'master_vars.csv'

### ISSUE THREAD

**Issue by jvtcl** [beckymasond/suffolk_USGS#8]
@beckymasond The ACS total code ('Universe Variable') for Race/Ethnicity in 'master_vars.csv' is incorrect (Total Households, 'ACS14_5yr_B25034001'). Please also verify, using a previous version of 'master_vars', that no other categories' total codes were overwritten.

**Comment by beckymasond** [comment]
Fixed for both 'race' and 'housing density.'
