### ISSUE TITLE
Age variable omission in 'data_prep.R'

### ISSUE THREAD

**Issue by jvtcl** [beckymasond/suffolk_USGS#9]
@beckymasond Age variables appear to be missing from the combined-category blockgroup estimates `data\rawACSdata_all\blockgroup_all_ests.csv`. I see that they're present in their own directory in `data\rawACSdata`, but to build the clustering inputs, I'm iterating over that combined-category file only.

**Comment by beckymasond** [comment]
I uploaded an updated version of that file yesterday. Age (T007) is in columns CA through CM (when viewed in Excel).

**Comment by jvtcl** [comment]
Oh, I see them now. I think the problem is actually on my end - looks like the variables are being omitted somewhere when I'm updating the names in `data_prep`...

**Comment by beckymasond** [comment]
Maybe because of the "SE_" at the front of the variable string?

**Comment by jvtcl** [comment]
Yeah, that or maybe the fact that my code is set up to strip the ending characters from the ACS variable names. I'll need to investigate further, so keeping this issue open.
